---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-api-config
  namespace: weather-app
  labels:
    project: weather-app
    app: api
data:
  REDIS_PORT: "6379"
  REDIS_HOST: "weather-app-redis.ipgeolocation.svc.cluster.local"
  APP_PORT: "8080"
  READINESS_DELAY_SEC: "30"